
/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */
var Item = require("./Item");
/**
 * Creates a instance of DidItem
 *
 * @constructor
 */
function DidItem() {
    this.phoneNumber = null;     
    this.trunkId = null;     
    this.didTypeHandle = null;     
    this.callerLocation = null;     
    //Append to variable dictionary
    this._variableDict['phoneNumber'] = 'phone_number';
    this._variableDict['trunkId'] = 'trunk_id';
    this._variableDict['didTypeHandle'] = 'did_type_handle';
    this._variableDict['callerLocation'] = '_caller_location';
}

DidItem.prototype = new Item();
DidItem.prototype.constructor = Item;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
DidItem.prototype.getPhoneNumber = function() {
    return this.phoneNumber;
};

/**
 * Setter for PhoneNumber
 * 
 * @param {string} value 
 */
DidItem.prototype.setPhoneNumber = function(value) {
    this.phoneNumber = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
DidItem.prototype.getTrunkId = function() {
    return this.trunkId;
};

/**
 * Setter for TrunkId
 * 
 * @param {int} value 
 */
DidItem.prototype.setTrunkId = function(value) {
    this.trunkId = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
DidItem.prototype.getDidTypeHandle = function() {
    return this.didTypeHandle;
};

/**
 * Setter for DidTypeHandle
 * 
 * @param {string} value 
 */
DidItem.prototype.setDidTypeHandle = function(value) {
    this.didTypeHandle = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {CallerLocation|null}
 */
DidItem.prototype.getCallerLocation = function() {
    return this.callerLocation;
};

/**
 * Setter for CallerLocation
 * 
 * @param {CallerLocation|null} value 
 */
DidItem.prototype.setCallerLocation = function(value) {
    this.callerLocation = value;
};

module.exports = DidItem;