
/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of Endpoint
 *
 * @constructor
 */
function Endpoint() {
    this.uri = null;     
    this.attrs = null;     
}

Endpoint.prototype = new BaseModel();
Endpoint.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Endpoint.prototype.getUri = function() {
    return this.uri;
};

/**
 * Setter for Uri
 * 
 * @param {string} value 
 */
Endpoint.prototype.setUri = function(value) {
    this.uri = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Endpoint.prototype.getAttrs = function() {
    return this.attrs;
};

/**
 * Setter for Attrs
 * 
 * @param {string} value 
 */
Endpoint.prototype.setAttrs = function(value) {
    this.attrs = value;
};

module.exports = Endpoint;