
/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of ItemForm
 *
 * @constructor
 */
function ItemForm() {
    this.item = null;     
}

ItemForm.prototype = new BaseModel();
ItemForm.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {Item}
 */
ItemForm.prototype.getItem = function() {
    return this.item;
};

/**
 * Setter for Item
 * 
 * @param {Item} value 
 */
ItemForm.prototype.setItem = function(value) {
    this.item = value;
};

module.exports = ItemForm;