
/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */
var Item = require("./Item");
/**
 * Creates a instance of LocationItem
 *
 * @constructor
 */
function LocationItem() {
    this.locationHandle = null;     
    this.quantity = null;     
    this.attributes = null;     
    this.didTypeHandle = null;     
    this.trunkId = null;     
    this.callerLocation = null;     
    //Append to variable dictionary
    this._variableDict['locationHandle'] = 'location_handle';
    this._variableDict['didTypeHandle'] = 'did_type_handle';
    this._variableDict['trunkId'] = 'trunk_id';
    this._variableDict['callerLocation'] = '_caller_location';
}

LocationItem.prototype = new Item();
LocationItem.prototype.constructor = Item;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LocationItem.prototype.getLocationHandle = function() {
    return this.locationHandle;
};

/**
 * Setter for LocationHandle
 * 
 * @param {string} value 
 */
LocationItem.prototype.setLocationHandle = function(value) {
    this.locationHandle = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
LocationItem.prototype.getQuantity = function() {
    return this.quantity;
};

/**
 * Setter for Quantity
 * 
 * @param {int} value 
 */
LocationItem.prototype.setQuantity = function(value) {
    this.quantity = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LocationItem.prototype.getAttributes = function() {
    return this.attributes;
};

/**
 * Setter for Attributes
 * 
 * @param {string} value 
 */
LocationItem.prototype.setAttributes = function(value) {
    this.attributes = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LocationItem.prototype.getDidTypeHandle = function() {
    return this.didTypeHandle;
};

/**
 * Setter for DidTypeHandle
 * 
 * @param {string} value 
 */
LocationItem.prototype.setDidTypeHandle = function(value) {
    this.didTypeHandle = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
LocationItem.prototype.getTrunkId = function() {
    return this.trunkId;
};

/**
 * Setter for TrunkId
 * 
 * @param {int} value 
 */
LocationItem.prototype.setTrunkId = function(value) {
    this.trunkId = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {CallerLocation|null}
 */
LocationItem.prototype.getCallerLocation = function() {
    return this.callerLocation;
};

/**
 * Setter for CallerLocation
 * 
 * @param {CallerLocation|null} value 
 */
LocationItem.prototype.setCallerLocation = function(value) {
    this.callerLocation = value;
};

module.exports = LocationItem;