
/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */
var RoutingBase = require("./RoutingBase");
/**
 * Creates a instance of Routing
 *
 * @constructor
 */
function Routing() {
    this.sipUser = null;     
    //Append to variable dictionary
    this._variableDict['sipUser'] = 'sip_user';
}

Routing.prototype = new RoutingBase();
Routing.prototype.constructor = RoutingBase;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Routing.prototype.getSipUser = function() {
    return this.sipUser;
};

/**
 * Setter for SipUser
 * 
 * @param {string} value 
 */
Routing.prototype.setSipUser = function(value) {
    this.sipUser = value;
};

module.exports = Routing;