
/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TelephoneNumberForm
 *
 * @constructor
 */
function TelephoneNumberForm() {
    this.telephoneNumber = null;     
    //Append to variable dictionary
    this._variableDict['telephoneNumber'] = 'telephone_number';
}

TelephoneNumberForm.prototype = new BaseModel();
TelephoneNumberForm.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {TelephoneNumber}
 */
TelephoneNumberForm.prototype.getTelephoneNumber = function() {
    return this.telephoneNumber;
};

/**
 * Setter for TelephoneNumber
 * 
 * @param {TelephoneNumber} value 
 */
TelephoneNumberForm.prototype.setTelephoneNumber = function(value) {
    this.telephoneNumber = value;
};

module.exports = TelephoneNumberForm;