
/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TelephoneNumber
 *
 * @constructor
 */
function TelephoneNumber() {
    this.trunkId = null;     
    this.sipEndPointUri = null;     
    this.alias = null;     
    this.channels = null;     
    this.routing = null;     
    //Append to variable dictionary
    this._variableDict['trunkId'] = 'trunk_id';
    this._variableDict['sipEndPointUri'] = 'sip_end_point_uri';
    this._variableDict['routing'] = '_routing';
}

TelephoneNumber.prototype = new BaseModel();
TelephoneNumber.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
TelephoneNumber.prototype.getTrunkId = function() {
    return this.trunkId;
};

/**
 * Setter for TrunkId
 * 
 * @param {int} value 
 */
TelephoneNumber.prototype.setTrunkId = function(value) {
    this.trunkId = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
TelephoneNumber.prototype.getSipEndPointUri = function() {
    return this.sipEndPointUri;
};

/**
 * Setter for SipEndPointUri
 * 
 * @param {string} value 
 */
TelephoneNumber.prototype.setSipEndPointUri = function(value) {
    this.sipEndPointUri = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
TelephoneNumber.prototype.getAlias = function() {
    return this.alias;
};

/**
 * Setter for Alias
 * 
 * @param {string} value 
 */
TelephoneNumber.prototype.setAlias = function(value) {
    this.alias = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
TelephoneNumber.prototype.getChannels = function() {
    return this.channels;
};

/**
 * Setter for Channels
 * 
 * @param {int} value 
 */
TelephoneNumber.prototype.setChannels = function(value) {
    this.channels = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {RoutingBase}
 */
TelephoneNumber.prototype.getRouting = function() {
    return this.routing;
};

/**
 * Setter for Routing
 * 
 * @param {RoutingBase} value 
 */
TelephoneNumber.prototype.setRouting = function(value) {
    this.routing = value;
};

module.exports = TelephoneNumber;