
/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of Token
 *
 * @constructor
 */
function Token() {
    this.isActive = null;     
    //Append to variable dictionary
    this._variableDict['isActive'] = 'is_active';
}

Token.prototype = new BaseModel();
Token.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {bool}
 */
Token.prototype.getIsActive = function() {
    return this.isActive;
};

/**
 * Setter for IsActive
 * 
 * @param {bool} value 
 */
Token.prototype.setIsActive = function(value) {
    this.isActive = value;
};

module.exports = Token;