
/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */
var Item = require("./Item");
/**
 * Creates a instance of TrunkItem
 *
 * @constructor
 */
function TrunkItem() {
    this.channels = null;     
    this.trunkHandle = null;     
    this.sipUri = null;     
    this.attributes = null;     
    this.routing = null;     
    //Append to variable dictionary
    this._variableDict['trunkHandle'] = 'trunk_handle';
    this._variableDict['sipUri'] = 'sip_uri';
    this._variableDict['routing'] = '_routing';
}

TrunkItem.prototype = new Item();
TrunkItem.prototype.constructor = Item;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
TrunkItem.prototype.getChannels = function() {
    return this.channels;
};

/**
 * Setter for Channels
 * 
 * @param {int} value 
 */
TrunkItem.prototype.setChannels = function(value) {
    this.channels = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
TrunkItem.prototype.getTrunkHandle = function() {
    return this.trunkHandle;
};

/**
 * Setter for TrunkHandle
 * 
 * @param {string} value 
 */
TrunkItem.prototype.setTrunkHandle = function(value) {
    this.trunkHandle = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
TrunkItem.prototype.getSipUri = function() {
    return this.sipUri;
};

/**
 * Setter for SipUri
 * 
 * @param {string} value 
 */
TrunkItem.prototype.setSipUri = function(value) {
    this.sipUri = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
TrunkItem.prototype.getAttributes = function() {
    return this.attributes;
};

/**
 * Setter for Attributes
 * 
 * @param {string} value 
 */
TrunkItem.prototype.setAttributes = function(value) {
    this.attributes = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {Routing}
 */
TrunkItem.prototype.getRouting = function() {
    return this.routing;
};

/**
 * Setter for Routing
 * 
 * @param {Routing} value 
 */
TrunkItem.prototype.setRouting = function(value) {
    this.routing = value;
};

module.exports = TrunkItem;