/**
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "https://api.magictelecom.com",
    APITOKEN : 'thisismysupperduppersecrettoken'

};

module.exports = configuration;

