/**
  * MagicTelecomAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 on 04/20/2016
  */

var configuration = require('./configuration');
var Hashes = require('./hashes');

var CustomAuthUtility = {

    /**
     * Appends the necessary custom credentials for making this authorized call
     * @param	{HttpRequest} request    The out going request to access the resource
     */
    appendCustomAuthParams:function(request) {
        // TODO: Add your custom authentication here
        // The following properties are available to use
        // 
        // ie. Add a header through:
        //request.headers["key"] = "value"
		var created = (new Date()).toISOString();
		var nonce = new Hashes.SHA512().b64(configuration.APITOKEN + Math.random());
		var digest = new Hashes.SHA1().b64(nonce + created + configuration.APITOKEN);
		var xwsse =  `UsernameToken Username="${configuration.USERNAME}", PasswordDigest="${digest}", Nonce="${nonce}", Created="${created}"`;
		
		request.headers["X-WSSE"] = xwsse;
    }
};

module.exports = CustomAuthUtility;